dist: bionic
language: cpp

compiler:
  - gcc

install:
  ############################################################################
  # All the dependencies are installed in ${HOME}/deps/
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.7-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
#  - |
#    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
#      CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.7-Linux-x86_64.tar.gz"
#      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
#      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
#    else
#      brew install cmake || brew upgrade cmake
#    fi
  - cmake --version

#addons:
#  snaps:
#    - name: cmake
#      confinement: classic # or devmode
#      channel: 3.14/stable # will be passed to --channel flag

before_script:
  # The 'install'used a different directoy, so we need to go back
  - cd "${TRAVIS_BUILD_DIR}"
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  # - make test
  - ./examples/Example
